Firecrest:
  ApiUrl: https://firecrest.cscs.ch
  TokenUrl: https://auth.cscs.ch/auth/realms/firecrest-clients/protocol/openid-connect/token
  Machine: daint
Environment:
  Variables:
    TEST_ENV_VAR: test-value
  PreRunCommandOnComputeNode: |
    echo "running precommand"
  PostRunCommandOnComputeNode: |
    echo "running postcommand"
    echo "Environment variable value: ${TEST_ENV_VAR}"
Resources:
  Queue: normal
  Nodes: 1
  NodeConstraints: gpu

