UnicoreApiUrl: https://unicore.dev2.cloud.mantik.ai/DEMO-SITE/rest/core
Resources:
  Nodes: 1
  Queue: batch
Environment:
  Variables:
    TEST_ENV_VAR: test-value
  PreRunCommandOnComputeNode: |
    echo "running precommand"
  PostRunCommandOnComputeNode: |
    echo "running postcommand"
    echo "Environment variable value: ${TEST_ENV_VAR}"
