UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Environment:
  PreRunCommand:
    ExecuteOnLoginNode: false
    Command: echo "running precommand"
  PostRunCommand:
    ExecuteOnLoginNode: false
    Command: echo "running postcommand"
Resources:
  Queue: devel
  Nodes: 1
