UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Environment:
  Variables:
    TEST_ENV_VAR: test-value
  PreRunCommandOnComputeNode: |
    echo "running precommand"
  PostRunCommandOnComputeNode: |
    echo "running postcommand"
    echo "Environment variable value: ${TEST_ENV_VAR}"
Resources:
  Queue: devel
  Nodes: 1
